### ISSUE TITLE
Error while extracting

### ISSUE THREAD

**Issue by rawatprince** [italorecife/OppoRealme-OFP-Flash#1]
Getting Extract error: error on super's. OFP super partition might be broken.

Device: Realme GT Master Edition

**Comment by italorecife** [comment]
could you send me the link of the .ofp package

**Comment by rawatprince** [comment]
Link to package: [Link](http://rms01.realme.net/SW/realme%20service/realme%20GT%20Master%20Edition/21675/RMX3360export_11_A.10_2022012002380000.zip)
