### ISSUE TITLE
Realme GT Bootloop after flashing EXPORT version

### ISSUE THREAD

**Issue by Lemuel2631** [italorecife/OppoRealme-OFP-Flash#11]
My phone keeps on returning to the bootloader after successful flashing RMX2202export_11_C.17

**Comment by Lemuel2631** [comment]
Need to rollback to stock frimware if you already change to other Region using TWRP

**Comment by MiaBhai99** [comment]
> My phone keeps on returning to the bootloader after successful flashing RMX2202export_11_C.17

Same problem here :/  Did you solve the issue with your device? And if yes, how?
