### ISSUE TITLE
May God give you everything in life

### ISSUE THREAD

**Issue by nikolasdan** [italorecife/OppoRealme-OFP-Flash#17]
What have you created is amaizing. You saved my phone and my fathers phone. As a reward I want to make a donation to you. Contact me please.

**Comment by italoalmeida0** [comment]
paypal: italorecife2@Live.com 
or: https://www.paypal.com/donate/?hosted_button_id=J5TGPEXNHUR4A

👍 You're welcome to help, if you need help you can call.
