### ISSUE TITLE
Celular não liga mais após uso da ferramenta

### ISSUE THREAD

**Issue by sminato27** [italorecife/OppoRealme-OFP-Flash#19]
Usei a ferramenta pra flashar a rom stock do GT 2 Pro e deu sucesso no terminal porém o celular não liga mais. Aparentemente os botões pararam de funcionar. Pode me ajudar? Tentei plugar na bateria e nem assim ele não liga.

**Comment by r-mathieu** [comment]
I recently had the same situation with my RMX3360 thinking I had done a hard brick after seeing that it would not turn on at all after a succesfull flash. I tried several times to turn it back on by holding down the Vol Up + Power or Vol Down + Power keys and it would turn back on.

**Comment by sminato27** [comment]
> I recently had the same situation with my RMX3360 thinking I had done a hard brick after seeing that it would not turn on at all after a succesfull flash. I tried several times to turn it back on by holding down the Vol Up + Power or Vol Down + Power keys and it would turn back on.

Mine was hard bricked but already got it back to live.
