### ISSUE TITLE
Can i rollback with this tool

### ISSUE THREAD

**Issue by mani4692** [italorecife/OppoRealme-OFP-Flash#3]
I flashed realme ui F.05 on top of realme ui 1.0 Android 10 with this .ofp flash tool it has flashed all partitions well and appears successful message but my realme 5pro device doesn't start booting (its going to fastboot) recovery also working fine
I don't know what to do now
Help pleace

**Comment by italorecife** [comment]
I need more information, what was the purpose of the flash at first?

**Comment by mani4692** [comment]
My realme 5 pro is in android 10 realme UI 1.0(c.15) I want to go for realme UI 2.0 f.03
I flashed f.03 with this tool on top of RUI 1.0 (c.15) flashing was successful but system doesn't booting( fastbbot& recovery works)
Then I rollback to android 10 RUI 1.0 (c.15)  then system boots into this version (RUI 1.0 (c.15) )
Note : 
I directly flashed f.03 on top of c.15 without formatting data in c.15recovery
I think it's not a problem
