### ISSUE TITLE
Does this work on all realme devices?

### ISSUE THREAD

**Issue by Ma8uru77** [italorecife/OppoRealme-OFP-Flash#4]
I have the Chinese Gt Neo 3 (Mediatek 8100) and once the global OFP file gets released I want to flash it using this tool. Will it work? Is there a chance it will brick my device or anything else that I should know?

**Comment by italorecife** [comment]
theoretically it works yes, but before you try it with your device is mediatek you can make a complete backup of the device with the download mode

**Comment by csfolmer** [comment]
> I have the Chinese Gt Neo 3 (Mediatek 8100) and once the global OFP file gets released I want to flash it using this tool. Will it work? Is there a chance it will brick my device or anything else that I should know?

Hi did you have the ofp file? O can't find it jet
