### ISSUE TITLE
Can't flash global (export ) rom, only gdpr 

### ISSUE THREAD

**Issue by Hryniuk1** [italorecife/OppoRealme-OFP-Flash#6]
System: Arch Linux
Version of android tools: 31.0.3-5
Version of Python: 3.10.5-1
Using Linux compiled *.bin file
My Device: Realme GT Master Edition RMX3363
My prebuilt firmware after buying and installing some OTA updates: Global rom C.06 region KE
Tested flashing via OFP Flash Tool: EU C.07, EU C.06 - device boots after flashing. Global C.07, C.06, A.10 any region - device bootloops, сhanging slots doesn't help. 
Flasher output is identical for EU and Global. ( "Файлы идентичны" on screenshot - Files are identical )
[EU.txt](https://github.com/italorecife/OppoRealme-OFP-Flash/files/8864534/EU.txt)
[RU.txt](https://github.com/italorecife/OppoRealme-OFP-Flash/files/8864535/RU.txt)
![Screenshot_20220608_222025](https://user-images.githubusercontent.com/29910078/172699506-4f3f2533-a8b2-406b-8bf6-02dac2c672c6.png)
Also, I unpacked *.ofp and compared checksums between gdpr and global firmware partitions. It was revealed that the difference between flashable partitions is only in super.img, vbmeta_system.img, vbmeta_vendor.img, userdata.img.
![Screenshot_20220608_215130](https://user-images.githubusercontent.com/29910078/172696120-9b1a2643-6f4a-47a8-8940-3894a7a4e4a7.png)
![Screenshot_20220608_215159](https://user-images.githubusercontent.com/29910078/172696124-9553a8eb-254b-48fd-b8d7-5c286c442f86.png)
![Screenshot_20220608_215218](https://user-images.githubusercontent.com/29910078/172696129-0e661d2c-e9df-4bca-b556-8b048e0b76d9.png)
![Screenshot_20220608_215238](https://user-images.githubusercontent.com/29910078/172696132-8eb960c1-d691-4d6d-9ae7-c045011e17a9.png)
I tried to flash the European firmware first, then flash the above partitions manually. The result is bootloop.
I thought, perhaps in the global firmware, the super.img partition is broken. I downloaded the OTA update from the RU region, unpacked 
it, also unpacked super.img from the global firmware, compared all partition, but their checksums turned out to be identical. 
![Screenshot_20220608_214837](https://user-images.githubusercontent.com/29910078/172696862-fb113a67-f4d8-4aac-a486-55cacf18e77e.png)
So super.img is not broken. 
This is photo taken from twrp after flashing global rom. Seems super partition is broken after flashing
![photo_2022-06-08_22-05-51](https://user-images.githubusercontent.com/29910078/172696967-91bc73f1-d9fa-4e4a-a623-e64439eae36b.jpg)
Also, I am attaching the imjtool output with information about the super partitions from export and gdpr, if this is of course necessary.
![Screenshot_20220608_221132](https://user-images.githubusercontent.com/29910078/172698020-7e65281d-7bd0-42ce-bd7c-9e365eace480.png)
![Screenshot_20220608_221206](https://user-images.githubusercontent.com/29910078/172698026-f8bc0c78-1fac-4928-8503-a40b76de011a.png)
What else to try, I do not know, I hope for your help

**Comment by italorecife** [comment]
as the flash is not complete, you can see from the failures presented by the flash logs, the partitions that are not changed simply do not let the system start the super different, only the ones they allow, for a more accurate flash you would have to change the partitions that fail with flash, for that I would need a rollback package as a reference and twrp, if you have some kind of complete stock package as a rollback package for your device, I can develop a package for twrp that will flash the missing partitions, thus making a complete flash.

**Comment by Hryniuk1** [comment]
> as the flash is not complete, you can see from the failures presented by the flash logs, the partitions that are not changed simply do not let the system start the super different
But after all, those partitions that are not flashed have the same checksum in gdpr and export, which means that these partitions will not change when flashing, because they are the same, so they should not affect the ability to boot. It is so?
What about rollback. Our device has it (RUI 3 A.12 to RUI 2 A.11) only for Indian firmware (which is codenamed RMX3360, not RMX3363), and there were reports that after flashing this rollback via twrp on RMX3363, the user also could not boot the phone. Here is the link: https://download.c.realme.com/flash/Rollbackpack/realme_GT_Master_Edition/RMX3360_11_A_fullota_00011011.zip
OTA (not rollback) with global firmware (RU region) may still be useful: here is the link - https://gauss-componentotacostmanual-eu.allawnofs.com/remove-944c1751113b4972398c2cef7e504287/component-ota/22/05/18/71331353f185492fa3efcf774f7e13a9.zip

**Comment by italorecife** [comment]
these partitions are not complete, they are just like the system part of each partition, the data part of the device is not changed, imagine if you flash the partition that contains the imei , and it was a complete partition, your device would go loses its imei, and network bands browsing configuration data, and stuff, so these partitions aren't complete and can't be, so when you check their hash they're the same, cuz it's just the partition system, no data from register.  and it may be that this registry data, may indicate what is needed to be initialized, like if super is compatible, or something like that.

I'll try to create a package for your device for twrp, as I did for gt neo 2, thus having a more complete flash.

**Comment by Hryniuk1** [comment]
Oh, I get it. Thanks, I'll appreciate it.

**Comment by italorecife** [comment]
try to flash the ota and then the .ofp package

**Comment by rahulkmr69** [comment]
Just came here to say that if you can't boot even after flashing OFP, then what finally worked for me was - 
1. ADB sideload the OTA package zip to BOTH SLOTS, i.e, flash it once, reboot recovery (it should automatically switch slots), flash it again.
2. Now flash OFP of the same version. Eg, if you flashed zip of C.05, flash OFP of C.05 here too.
3. Reboot to recovery -> Wipe data, reboot to system. At this point you either boot RealmeUI or bootloop back to bootloader.
4. If it comes back to bootloader, switch slots using fastboot command and again reboot to recovery -> Wipe data.
5. Now reboot to system, it will boot hopefully 🙏

**Comment by Hryniuk1** [comment]
@rahulkmr69 YESSS
Your guide is worked for me, I've successfully flashed RU region!
Thank you very much!

**Comment by LeoKesler** [comment]
> I'll try to create a package for your device for twrp, as I did for gt neo 2, thus having a more complete flash.

Hi, what package or where is the package for gt neo 2 ?

I bought the gt neo 2 and I received the EU version, with GDPR firmware, without call recording. I am searching for a way to flash the India version to get the call recording.

I want the Indian version because I think it is the most complete version.

**Comment by italorecife** [comment]
> > I'll try to create a package for your device for twrp, as I did for gt neo 2, thus having a more complete flash.
> 
> Hi, what package or where is the package for gt neo 2 ?
> 
> I bought the gt neo 2 and I received the EU version, with GDPR firmware, without call recording. I am searching for a way to flash the India version to get the call recording.
> 
> I want the Indian version because I think it is the most complete version.

https://forum.xda-developers.com/t/bitra-realme-ui-flashable-stock-firmware-packages-for-twrp-change-region.4426659/

**Comment by LeoKesler** [comment]
> > > I'll try to create a package for your device for twrp, as I did for gt neo 2, thus having a more complete flash.
> > 
> > 
> > Hi, what package or where is the package for gt neo 2 ?
> > I bought the gt neo 2 and I received the EU version, with GDPR firmware, without call recording. I am searching for a way to flash the India version to get the call recording.
> > I want the Indian version because I think it is the most complete version.
> 
> https://forum.xda-developers.com/t/bitra-realme-ui-flashable-stock-firmware-packages-for-twrp-change-region.4426659/

HELP!

I did the procedure, first video and I got the chinese bootloader. Select English, next screen still in chinese.
Select the second option to wipe ( looking the position using your video).  
The screen show a code. But the touch do not work.

I am unable to shutdown the phone. Or reset the phone. It is freeze.

I tried to flash the Indian rom. Unlocked bootloader.

**Comment by italorecife** [comment]
> > > > I'll try to create a package for your device for twrp, as I did for gt neo 2, thus having a more complete flash.
> > > 
> > > 
> > > Hi, what package or where is the package for gt neo 2 ?
> > > I bought the gt neo 2 and I received the EU version, with GDPR firmware, without call recording. I am searching for a way to flash the India version to get the call recording.
> > > I want the Indian version because I think it is the most complete version.
> > 
> > 
> > https://forum.xda-developers.com/t/bitra-realme-ui-flashable-stock-firmware-packages-for-twrp-change-region.4426659/
> 
> For some reason, after some time, I able to use volume up and power to shutdown. After that, next power on, I able to use the bootloader and type the code to format the phone.
> 
> After some minutes, it worked.
> 
> ## Ignore.
> HELP!
> 
> I did the procedure, first video and I got the chinese bootloader. Select English, next screen still in chinese. Select the second option to wipe ( looking the position using your video). The screen show a code. But the touch do not work.
> 
> I am unable to shutdown the phone. Or reset the phone. It is freeze.
> 
> I tried to flash the Indian rom. Unlocked bootloader.

você tem telegram?

**Comment by LeoKesler** [comment]
> você tem telegram?

Eu consegui resolver depois de um tempo. Depois de uns 15minutos de terror, ele aceitou o comando power + vol up e desligou. Liguei novamente e consegui digitar o codigo para autorizar o clear data.

Sobre meu telegram, eu tenho, mas o pouco que eu uso é via PC, então nem tenho link de contato... Só estou usando agora para pegar info sobre o phone. Eu estou no grupo Realme GT Neo 2 Br, usuario Lucas. Postei agora há pouco mensagem perguntando se há forma de melhorar a qualidade da gravação de conversas telefonicas.
