### ISSUE TITLE
Is installation possible?

### ISSUE THREAD

**Issue by AgafDL** [italorecife/OppoRealme-OFP-Flash#7]
Hello. There is a REALME Q3S (RMX3461) smartphone with global firmware, Kenya region. There is a clone, Realme 9 5G SE (RMX3461) with global firmware, India region. The bootloader is unlocked on the Realme Q3S smartphone, there is an OFP firmware from Realme 9 5G SE. Can I install a firmware from the Realme 9 5G SE smartphone? Will the installation of a smartphone break down?

Realme Q3s:
[ro.boot.prjname]: [21643]
[ro.build.oplus_nv_id]: [01110100]
[ro.build.product]: [RMX3461T2]
[ro.product.device]: [RE548BL1]
[ro.product.product.name]: [RMX3461T2]
[ro.product.system.name]: [RMX3461T2]
[ro.product.vendor.name]: [RMX3461T2]
[ro.product.bootimage.model]: [RMX3461]
[ro.product.bootimage.name]: [RMX3461T2]
[ro.product.model]: [RMX3461]
[ro.product.odm.model]: [RMX3461]

Realme 9 5G SE:
[ro.boot.prjname]: [21695]
[ro.build.oplus_nv_id]: [00011011]
[ro.build.product]: [RMX3461]
[ro.product.device]: [RE54BFL1]
[ro.product.product.name]: [RMX3461]
[ro.product.system.name]: [RMX3461]
[ro.product.vendor.name]: [RMX3461]
[ro.product.bootimage.model]: [RMX3461]
[ro.product.bootimage.name]: [RMX3461]
[ro.product.model]: [RMX3461]
[ro.product.odm.model]: [RMX3461]

I will attach the Getprop file from these two smartphone models. Please, help.

[getprop_A06_Realme_9_5g_se.txt](https://github.com/italorecife/OppoRealme-OFP-Flash/files/8918638/getprop_A06_Realme_9_5g_se.txt)
[getprop_A03_Realme_Q3s.txt](https://github.com/italorecife/OppoRealme-OFP-Flash/files/8918639/getprop_A03_Realme_Q3s.txt)

**Comment by italorecife** [comment]
I made a twrp package for your device

https://forum.xda-developers.com/t/rmx3461-realme-ui-flashable-stock-firmware-packages-for-twrp-change-region.4460459/
